apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  opensearch.yml: |
    cluster.name: os-cluster
    network.host: 0.0.0.0
    discovery.seed_hosts: opensearch
    cluster.initial_master_nodes: opensearch-master-0 # put here the name of all your master nodes

    plugins.security.allow_unsafe_democertificates: true
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemtrustedcas_filepath: certificates/ca/ca.pem
    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/ca/ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false

    plugins.security.ssl.transport.pemkey_filepath: certificates/opensearch/opensearch.key # relative path
    plugins.security.ssl.transport.pemcert_filepath: certificates/opensearch/opensearch.pem
    plugins.security.ssl.http.pemkey_filepath: certificates/opensearch/opensearch.key
    plugins.security.ssl.http.pemcert_filepath: certificates/opensearch/opensearch.pem

    plugins.security.authcz.admin_dn:
      - 'CN=ADMIN,O=UN,L=UN,ST=UN,C=UN'
    plugins.security.nodes_dn:
      - 'CN=opensearch,O=UN,L=UN,ST=UN,C=UN'
